### ISSUE TITLE
Cannot set time error

### ISSUE THREAD

**Issue by jacklisp** [nbdd0121/wsld#10]
Hi,I can run wsldhost.exe --daemon in windows, after that i ran the follow command in WSL
```
~$ wsld &
```
Then I got this error, how can I fix it?
```
Received time 2021-02-10T08:09:08.882769Z, clock off by 2ms 982us, adjust
Cannot set time, run with root or set CAP_SET_TIME
Timekeeper error: Operation not permitted (os error 1)
```

**Comment by nbdd0121** [comment]
From README.md:
> If you need time synchronisation, you should either run wsld with root, or give it `cap_sys_time` capability using `sudo setcap cap_sys_time+eip <PATH to wsld>`.

The error message also pointed out the solution for you.
