### ISSUE TITLE
Downloading Binaries From Actions?

### ISSUE THREAD

**Issue by bubalis** [nbdd0121/wsld#14]
The binaries fail to compile on my machine, I saw that others have had this problem, but downloading the pre-built binaries worked for them.

However, after several hours in the github documentation, I have no idea what it means to "download pre-built binaries from GitHub Actions artifacts" or how to do it. 

Any chance you can point me in the right direction?
Thanks

**Comment by nbdd0121** [comment]
Click the latest commit, currently https://github.com/nbdd0121/wsld/actions/runs/591360433, you can see the "Artifacts" section.

**Comment by Safrone** [comment]
@nbdd0121 Expired

**Comment by nbdd0121** [comment]
Now available from releases page.
