### ISSUE TITLE
Failed to listen: No such file or directory (os error 2) (on windows 11)

### ISSUE THREAD

**Issue by idanz** [nbdd0121/wsld#17]
Trying to run WSLD in WSL2 on Windows 11, results in : 
Failed to listen: No such file or directory (os error 2)

**Comment by nbdd0121** [comment]
Can you check that:
* File `/tmp/.X0-lock` doesn't exist
* wsld have permission to write in `/tmp/.X11-unix`?

**Comment by idanz** [comment]
Thanks for the quick reply!

You were right, it seems wslg created a link on /tmp/.X11-unix and that caused the issue
> ls -ll /tmp/.X11-unix
lrwxrwxrwx 1 root root 19 Oct 29 17:30 /tmp/.X11-unix -> /mnt/wslg/.X11-unix

removing the link and starting wsld again solved the issue
