### ISSUE TITLE
Compile error when going cargo install in wsl2

### ISSUE THREAD

**Issue by frumioj** [nbdd0121/wsld#25]
Compiling wsld v0.1.0 (/home/frumioj/.cargo/git/checkouts/wsld-339d41e00be8b46a/524d541/client)
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
  --> client/src/tcp.rs:37:45
   |
37 |             libc::AF_INET => SocketAddr::V4(mem::transmute(
   |                                             ^^^^^^^^^^^^^^
   |
   = note: source type: `sockaddr_in` (128 bits)
   = note: target type: `SocketAddrV4` (48 bits)

For more information about this error, try `rustc --explain E0512`.
error: could not compile `wsld` due to previous error
error: failed to compile `wsld v0.1.0 (https://github.com/nbdd0121/wsld#524d541f)`, intermediate artifacts can be found at `/tmp/cargo-installNde0uS`
j

(resolved by using the -- rather old -- binary release of wsld)

**Comment by nbdd0121** [comment]
Thank you for reporting. Fixed.
