### ISSUE TITLE
WSLD with no admin rights using VMID from registry

### ISSUE THREAD

**Issue by PauliusMorku** [nbdd0121/wsld#31]
Hello,
I started working on a corporate PC and need to run WSLD with normal user rights. It seems like this feature is not supported currently, but I managed to make it work by providing WSLD with VMID like so: `wsldhost.exe AB4A63F1-79B4-482E-AB9E-2CCD11314700`. I was about to write a script that gets VMID from registry like described [here](https://github.com/nbdd0121/wsld/issues/8) and passes it as an argument to wsldhost.exe.  But then I realized that WSLD already has [code](https://github.com/nbdd0121/wsld/commit/7096d406609c71c57bae5ed321c743336c35ccce) that is supposed to do that. However, when I simply run wsldhost.exe with no elevated rights I get this 
![image](https://user-images.githubusercontent.com/5755920/228767054-96474379-c36f-4296-8078-d914310c3bf9.png)
Its seems like WSLD could easily run with no elevated rights, but there is some unwanted feature/bug that prevents it from doing so. Would it be possible to fix it? That would be such a great feature to allow this brilliant tool to run without admin rights.
Best,
Paulius

**Comment by PauliusMorku** [comment]
That one seems to launch fine without providing anything. However, if WSL is restarted then WSLD does not seem to refresh, and if it is launched without WSL running then it freaks out.
![image](https://user-images.githubusercontent.com/5755920/228887174-9a0115ec-6158-47bc-b8d8-644c0a5e8456.png)
It would be an awesome feature if it could monitor/poll registry and refresh itself if the VMID is present and just idle otherwise.

**Comment by nbdd0121** [comment]
There is already a `--daemon` flag that does the regular polling.

**Comment by PauliusMorku** [comment]
My bad, forgot to try it :) Tested and seems to work fine!
