### ISSUE TITLE
Feature: focus root window when XServer window loses focus

### ISSUE THREAD

**Issue by oxc** [nbdd0121/wsld#9]
I am facing an unnerving issue with IntelliJ IDEA running in WSL: 
* when IntelliJ loses focus, it checks for file changes that have been done outside the application (e.g. a git pull in the project directory)
* when I switch from IntelliJ to a different X11 application window, the FocusOut event is properly dispatched to the window
* however, when I switch from IntelliJ to a Windows application window (e.g. Windows Terminal), no such event is dispatched, and IntellIJ does not refresh when I switch back.

This seems to only apply to Java-based application, probably because they are using a separate "focus proxy" child window, which is not the window the X server is displaying, but still has the native focus.

For other X11 applications I use, when I unfocus the XServer application window, the native focus gets set to the root window.

If I simulate this behaviour by manually setting the focus to the root window after I move from IntelliJ to the terminal, things work as expected.

Would it be possible to integrate this behaviour into wsld? Whenever the wsldhost detects a window belonging to the Xserver being unfocused, it sends a command to wsld to set the X focus to the root window.

**Comment by nbdd0121** [comment]
That sounds like the job for your particular X server of choice, since WSLD only forwards the X connection. WSLD does not itself understands the X protocol other than how to accept and make a connection.

**Comment by oxc** [comment]
I'm aware of that, and I agree. But since all servers I tried share that behavior, and wsld seems to have become a collection of workarounds for the kinks of WSL, I thought it might fit anyway.

I'll try to raise an issue with vcxsrv and see where that goes.
